registry:
  auto_register: true
  models:
    - model_id: "openai:gpt-4o"
      model_name: "gpt-4o"
      cost:
        input_cost_per_million: 5000   # $5.00 per million input tokens
        output_cost_per_million: 15000 # $15.00 per million output tokens
      rate_limit:
        tokens_per_minute: 10000000    # Up to 10 million tokens per minute
        requests_per_minute: 1500      # Tier 5 rate limit
      provider:
        name: "OpenAI"
        default_api_key: "${OPENAI_API_KEY}"
        base_url: "https://api.openai.com"

    - model_id: "openai:gpt-4o-mini"
      model_name: "gpt-4o-mini"
      cost:
        input_cost_per_million: 150    # $0.15 per million input tokens
        output_cost_per_million: 600   # $0.60 per million output tokens
      rate_limit:
        tokens_per_minute: 10000000
        requests_per_minute: 1500
      provider:
        name: "OpenAI"
        default_api_key: "${OPENAI_API_KEY}"
        base_url: "https://api.openai.com"

    - model_id: "openai:o1"
      model_name: "o1"
      cost:
        input_cost_per_million: 10000
        output_cost_per_million: 20000
      rate_limit:
        tokens_per_minute: 5000000
        requests_per_minute: 1000
      provider:
        name: "OpenAI"
        default_api_key: "${OPENAI_API_KEY}"
        base_url: "https://api.openai.com"

      